# Generated by Django 2.0.3 on 2019-03-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='pickup_date',
            field=models.CharField(max_length=15),
        ),
    ]
