# Generated by Django 2.0.3 on 2019-03-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
